#!/usr/bin/env python3
"""
Generate Multi-Server Aggregated Summary Plots

Usage:
    python scripts/generate_multiserver_summary.py --input_dir data/all_servers_results --output_dir reports/multiserver_summary

This script should be run MANUALLY after collecting the results from all servers in the campaign.
The `input_dir` must contain subdirectories for each server (e.g., server_A, server_B).
Each server subdirectory must contain the consolidated CSVs generated by `generate_ilp_report_assets.py` in its `csv` folder, such as:
    - ilp_best_per_model.csv
    - ilp_pareto_consolidated.csv
"""

import argparse
from pathlib import Path
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
sns.set_palette("colorblind")

def plot_speedup_distribution(best_df: pd.DataFrame, out_dir: Path):
    if "all_cpu_objective" not in best_df.columns or "ilp_objective" not in best_df.columns:
        return
        
    df = best_df.copy()
    df["all_cpu_objective"] = pd.to_numeric(df["all_cpu_objective"], errors="coerce")
    df["ilp_objective"] = pd.to_numeric(df["ilp_objective"], errors="coerce")
    
    # Filter valid rows
    df = df[(df["all_cpu_objective"] > 0) & (df["ilp_objective"] > 0)].copy()
    df["speedup_vs_cpu"] = df["all_cpu_objective"] / df["ilp_objective"]
    
    fig, ax = plt.subplots(figsize=(12, 6))
    sns.violinplot(data=df, x="server_name", y="speedup_vs_cpu", ax=ax, density_norm="width", inner="quartile", palette="muted")
    
    ax.axhline(y=1.0, color='r', linestyle='--', linewidth=2, label="Baseline (All-CPU)")
    ax.set_title("Distribution of ILP Speedup vs All-CPU across Servers", pad=15, fontweight="bold")
    ax.set_ylabel("Speedup Ratio (Higher is Better)", fontweight="bold")
    ax.set_xlabel("Server Hardware", fontweight="bold")
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right")
    ax.legend()
    
    sns.despine()
    fig.tight_layout()
    fig.savefig(out_dir / "speedup_distribution_violin.png", dpi=300)
    plt.close(fig)

def plot_feasibility_stacked_bar(best_df: pd.DataFrame, out_dir: Path):
    if "ilp_status" not in best_df.columns:
        return
        
    df = best_df.copy()
    
    def determine_outcome(row):
        ilp_status = str(row.get("ilp_status", "")).lower()
        if ilp_status not in ["optimal", "feasible"]:
            return "ILP OOM / Infeasible"
            
        ilp_obj = pd.to_numeric(row.get("ilp_objective", np.nan), errors="coerce")
        cpu_obj = pd.to_numeric(row.get("all_cpu_objective", np.nan), errors="coerce")
        
        if pd.isna(ilp_obj) or pd.isna(cpu_obj):
            return "Unknown"
            
        if ilp_obj < cpu_obj:
            return "ILP Faster than CPU"
        else:
            return "CPU Faster / Tie"
            
    df["outcome"] = df.apply(determine_outcome, axis=1)
    
    # Group by server and outcome
    counts = df.groupby(["server_name", "outcome"]).size().unstack(fill_value=0)
    
    # Normalize to percentages
    percentages = counts.div(counts.sum(axis=1), axis=0) * 100
    
    fig, ax = plt.subplots(figsize=(10, 6))
    percentages.plot(kind="bar", stacked=True, ax=ax, colormap="viridis")
    
    ax.set_title("ILP Feasibility and Win-Rate by Server", pad=15, fontweight="bold")
    ax.set_ylabel("Percentage of Configurations (%)", fontweight="bold")
    ax.set_xlabel("Server Hardware", fontweight="bold")
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right")
    ax.legend(title="Outcome", bbox_to_anchor=(1.05, 1), loc='upper left')
    
    sns.despine()
    fig.tight_layout()
    fig.savefig(out_dir / "feasibility_stacked_bar.png", dpi=300)
    plt.close(fig)

def plot_global_pareto_scatter(pareto_df: pd.DataFrame, out_dir: Path):
    if "gpu_budget_mb" not in pareto_df.columns or "ilp_objective" not in pareto_df.columns:
        return
        
    df = pareto_df.copy()
    df["ilp_objective"] = pd.to_numeric(df["ilp_objective"], errors="coerce")
    df["gpu_budget_mb"] = pd.to_numeric(df["gpu_budget_mb"], errors="coerce")
    df["all_cpu_objective"] = pd.to_numeric(df["all_cpu_objective"], errors="coerce")
    
    df = df[(df["ilp_objective"] > 0) & (df["all_cpu_objective"] > 0)].copy()
    
    # Normalize objective to speedup
    df["speedup"] = df["all_cpu_objective"] / df["ilp_objective"]
    
    fig, ax = plt.subplots(figsize=(12, 8))
    
    # Use scatterplot with hue=server_name
    sns.scatterplot(data=df, x="gpu_budget_mb", y="speedup", hue="server_name", alpha=0.6, s=50, ax=ax, edgecolor=None)
    
    ax.axhline(y=1.0, color='r', linestyle='--', linewidth=2, label="Baseline (All-CPU)")
    ax.set_title("Global Pareto Frontier: Speedup vs VRAM Budget", pad=15, fontweight="bold")
    ax.set_ylabel("Speedup vs All-CPU", fontweight="bold")
    ax.set_xlabel("GPU Memory Budget (MB)", fontweight="bold")
    ax.legend(title="Server Hardware", bbox_to_anchor=(1.05, 1), loc='upper left')
    
    sns.despine()
    fig.tight_layout()
    fig.savefig(out_dir / "global_pareto_scatter.png", dpi=300)
    plt.close(fig)

def main():
    parser = argparse.ArgumentParser(description="Generate Multi-Server Aggregated Summary Plots")
    parser.add_argument("--input_dir", type=str, required=True, help="Directory containing subfolders for each server's results")
    parser.add_argument("--output_dir", type=str, required=True, help="Directory to save the multiserver plots")
    args = parser.parse_args()

    input_root = Path(args.input_dir)
    output_root = Path(args.output_dir)
    output_root.mkdir(parents=True, exist_ok=True)

    if not input_root.exists() or not input_root.is_dir():
        print(f"Error: input_dir {input_root} does not exist or is not a directory.")
        return

    best_frames = []
    pareto_frames = []

    # Iterate over server subdirectories
    for server_dir in input_root.iterdir():
        if not server_dir.is_dir():
            continue
            
        server_name = server_dir.name
        
        # Look for ilp_best_per_model.csv and ilp_pareto_consolidated.csv
        # They might be directly in server_dir or inside a 'csv' subfolder
        best_csv = list(server_dir.rglob("ilp_best_per_model.csv"))
        pareto_csv = list(server_dir.rglob("ilp_pareto_consolidated.csv"))
        
        if best_csv:
            df = pd.read_csv(best_csv[0])
            df["server_name"] = server_name
            best_frames.append(df)
            
        if pareto_csv:
            df = pd.read_csv(pareto_csv[0])
            df["server_name"] = server_name
            pareto_frames.append(df)

    if not best_frames and not pareto_frames:
        print(f"No valid consolidated CSV files found in subdirectories of {input_root}.")
        return

    print(f"Processing data for {len(best_frames)} servers...")

    if best_frames:
        all_best_df = pd.concat(best_frames, ignore_index=True)
        plot_speedup_distribution(all_best_df, output_root)
        plot_feasibility_stacked_bar(all_best_df, output_root)
        print("Generated Speedup Distribution and Feasibility plots.")
        
    if pareto_frames:
        all_pareto_df = pd.concat(pareto_frames, ignore_index=True)
        plot_global_pareto_scatter(all_pareto_df, output_root)
        print("Generated Global Pareto Scatter plot.")

    print(f"Multi-server summary plots successfully generated in {output_root}")

if __name__ == "__main__":
    main()
