#!/bin/bash

# =======================================================================================
# QUICK REFERENCE: Project Setup & Common Tasks
# =======================================================================================

echo "========================================================================"
echo "ADVANCED HYBRID PROFILER - QUICK START GUIDE"
echo "========================================================================"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}1. INSTALLATION${NC}"
echo "   ┌─ Option A: Conda (Recommended)"
echo "   │  conda env create -f config/environment.yml"
echo "   │  conda activate thesis_env"
echo "   └─"
echo ""
echo "   ┌─ Option B: Pip + Manual PyTorch Install"
echo "   │  pip install -r config/requirements.txt"
echo "   │  pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121"
echo "   └─"
echo ""

echo -e "${BLUE}2. VERIFY INSTALLATION${NC}"
echo "   bash validation/run_unit_tests.sh"
echo "   python validation/validate_code.py"
echo "   python validation/validate_all_models.py --preflight-scope fast"
echo "   python validation/validate_zombie_fix.py"
echo "   bash validation/comprehensive_check.sh"
echo ""

echo -e "${BLUE}3. PROFILE SINGLE MODEL${NC}"
echo ""
echo "   ┌─ First-time dataset preparation"
echo "   │  python scripts/download_datasets.py --models all --datasets_root datasets"
echo "   └─"
echo ""
echo "   ┌─ Example: ViT-B/16 GPU-only (no CPU FP16 blocking)"
echo "   │  python src/profiler.py \\"
echo "   │    --model vit_b16 \\"
echo "   │    --precision fp32 \\" 
echo "   │    --datasets_root datasets \\" 
echo "   │    --require_datasets \\" 
echo "   │    --skip_cpu \\"
echo "   │    --num_threads 16 \\"
echo "   │    --batch_size 32"
echo "   └─ Output: data/{hostname}/.../vit_b16_metrics.csv"
echo ""
echo "   ┌─ Example: ResNet50 with CPU + GPU profiling"
echo "   │  python src/profiler.py \\"
echo "   │    --model resnet50 \\"
echo "   │    --precision fp32 \\"
echo "   │    --batch_size 64 \\"
echo "   │    --rapl  (for CPU energy)"
echo "   └─"
echo ""

echo -e "${BLUE}4. RUN FULL EXPERIMENT GRID${NC}"
echo "   bash scripts/run_experiments.sh"
echo "   # Uses the current grid configured inside scripts/run_experiments.sh"
echo ""

echo -e "${BLUE}5. THESIS SMOKE WORKFLOW${NC}"
echo "   bash scripts/run_thesis_smoke_workflow.sh"
echo "   # Reduced end-to-end workflow: profiling -> aggregation -> ILP -> plots -> LaTeX"
echo ""

echo -e "${BLUE}6. IMPORTANT COMMAND-LINE FLAGS${NC}"
echo "   ┌─ Operational Flags"
echo "   │  --skip_cpu              Skip CPU profiling entirely"
echo "   │  --num_threads N         Force N CPU threads (override SLURM)"
echo "   │  --datasets_root path    Dataset root used by supported models"
echo "   │  --require_datasets      Fail instead of silently falling back"
echo "   └─"
echo ""
echo "   ┌─ Standard Flags"
echo "   │  --model {name}          Model: resnet50/resnet152/vit_b16/bert_base/gpt2_small/distilgpt2/simple_mlp"
echo "   │  --batch_size N          Batch size (8-256 typical)"
echo "   │  --precision {mode}      fp32/fp16/bf16"
echo "   │  --warmup N              Warmup iterations (default: 5)"
echo "   │  --measure N             Measurement iterations (default: 15)"
echo "   │  --optimizer {name}      SGD/Adam/AdamW/RMSprop/Adagrad/Adadelta"
echo "   │  --output_dir path       Output directory (default: data)"
echo "   │  --rapl                  Enable CPU RAPL energy (Linux only)"
echo "   │  --no_gpu                CPU-only profiling"
echo "   └─"
echo ""

echo -e "${BLUE}7. OUTPUT FILES${NC}"
echo "   ┌─ Structure: data/{hostname}/results/{model}/{optimizer}/{precision}/batch_{N}/run_*/"
echo "   │"
echo "   ├─ {model}_metrics.csv           ← Per-layer execution metrics (ILP input)"
echo "   ├─ {model}_meta.json             ← Hardware metadata, energy totals"
echo "   ├─ {model}_graph_edges.csv       ← Graph edges for ILP/runtime"
echo "   ├─ {model}_transfer_edges.csv    ← Transfer costs between layers"
echo "   └─ {model}_metrics_stats.csv     ← Aggregated metrics across runs"
echo ""

echo -e "${BLUE}8. DIRECTORY STRUCTURE${NC}"
echo "   project/"
echo "   ├── config/"
echo "   │   ├── environment.yml"
echo "   │   └── requirements.txt"
echo "   ├── datasets/                    ← Dataset storage root"
echo "   ├── scripts/"
echo "   │   ├── run_experiments.sh       ← Master experiment script"
echo "   │   ├── run_thesis_mode.sh       ← Thesis-grade orchestration"
echo "   │   └── launch_grid5k.sh         ← HPC submission"
echo "   ├── src/                         ← Profiling, ILP, runtime, datasets"
echo "   ├── data/"
echo "   │   └── <hostname>/results/      ← Generated metrics per server/node"
echo "   ├── logs/"
echo "   │   └── experiments_*.txt        ← Execution logs"
echo "   ├── reports/                     ← ILP/report assets"
echo "   ├── tests/                       ← Unit tests"
echo "   ├── validation/                  ← Validation scripts"
echo "   ├── docs/                        ← Documentation"
echo "   ├── thesis/                      ← LaTeX manuscript and PDF"
echo "   └── README.md                    ← Root operational overview"
echo ""

echo -e "${BLUE}9. TROUBLESHOOTING${NC}"
echo "   Problem: Process hangs at batch X"
echo "   ↳ Cause: ViT-B/16 FP16 on CPU without AVX512_FP16 (C++ emulation blocks)"
echo "   ↳ Fix: Use --skip_cpu or --precision fp32"
echo ""
echo "   Problem: OOM (Out of Memory)"
echo "   ↳ Fix: Reduce batch_size or use --skip_cpu to reduce memory usage"
echo ""
echo "   Problem: Permission denied on RAPL"
echo "   ↳ Fix: Don't use --rapl, or run with sudo (not recommended)"
echo ""

echo -e "${BLUE}10. MONITORING EXECUTION${NC}"
echo "   # Terminal 1: Start experiments"
echo "   bash scripts/run_experiments.sh"
echo ""
echo "   # Terminal 2: Monitor progress"
echo "   tail -f logs/experiments_*.txt"
echo ""
echo "   # Terminal 3: Check output files"
echo "   ls -R data/*/results/"
echo ""

echo -e "${BLUE}11. RECOMMENDED WORKFLOWS${NC}"
echo ""
echo "   ┌─ Profile 0 (preflight on every server)"
echo "   │  Use: SMOKE_MODE=true DRY_RUN=true FAIL_FAST=true bash scripts/run_experiments.sh"
echo "   │  Purpose: validate interpreter, GPU detection, command construction"
echo "   └─"
echo ""
echo "   ┌─ Profile 5 (real smoke per server class)"
echo "   │  Use: canonical minimal real run before broad collection"
echo "   │  See: docs/SERVER_LAUNCH_PROFILES.md"
echo "   └─"
echo ""
echo "   ┌─ Multi-node ILP merge"
echo "   │  Use: bash scripts/discover_ilp_config_dirs.sh"
echo "   │  See: docs/MULTI_NODE_ILP_RUNBOOK.md"
echo "   └─"
echo ""

echo "========================================================================"
echo -e "${GREEN}✓ Project setup complete!${NC}"
echo "========================================================================"
echo ""
echo "Next steps:"
echo "  1. Verify installation: bash validation/run_unit_tests.sh"
echo "  2. Profile a model: python src/profiler.py --model simple_mlp"
echo "  3. Read docs/README.md and docs/PROJECT_STRUCTURE.md"
echo ""
