#!/bin/bash

# =======================================================================================
# QUICK REFERENCE: Project Setup & Common Tasks
# =======================================================================================

echo "========================================================================"
echo "ADVANCED HYBRID PROFILER - QUICK START GUIDE"
echo "========================================================================"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}1. INSTALLATION${NC}"
echo "   ┌─ Option A: Conda (Recommended)"
echo "   │  conda env create -f config/environment.yml"
echo "   │  conda activate thesis_env"
echo "   └─"
echo ""
echo "   ┌─ Option B: Pip + Manual PyTorch Install"
echo "   │  pip install -r config/requirements.txt"
echo "   │  pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121"
echo "   └─"
echo ""

echo -e "${BLUE}2. VERIFY INSTALLATION${NC}"
echo "   python validation/validate_code.py"
echo "   python validation/validate_all_models.py --preflight-scope fast"
echo "   python validation/validate_zombie_fix.py"
echo ""

echo -e "${BLUE}3. PROFILE SINGLE MODEL${NC}"
echo ""
echo "   ┌─ Example: ViT-B/16 GPU-only (no CPU FP16 blocking)"
echo "   │  python src/profiler.py \\"
echo "   │    --model vit_b16 \\"
echo "   │    --precision fp16 \\"
echo "   │    --skip_cpu \\"
echo "   │    --num_threads 16 \\"
echo "   │    --batch_size 32"
echo "   └─ Output: data/{hostname}/.../vit_b16_metrics.csv"
echo ""
echo "   ┌─ Example: ResNet50 with CPU + GPU profiling"
echo "   │  python src/profiler.py \\"
echo "   │    --model resnet50 \\"
echo "   │    --precision fp32 \\"
echo "   │    --batch_size 64 \\"
echo "   │    --rapl  (for CPU energy)"
echo "   └─"
echo ""

echo -e "${BLUE}4. RUN FULL EXPERIMENT GRID${NC}"
echo "   bash scripts/run_experiments.sh"
echo "   # Profiles all 6 models × 7 optimizers × 3 precisions × 6 batches"
echo ""

echo -e "${BLUE}5. QUICK TEST (All Models, Same Config)${NC}"
echo "   for model in resnet50 resnet152 vit_b16 bert_base gpt2_small simple_mlp; do"
echo "     echo \"Testing: \$model\""
echo "     python src/profiler.py --model \$model --batch_size 8 --precision fp32 \\"
echo "       --warmup 1 --measure 3 --skip_cpu"
echo "   done"
echo ""

echo -e "${BLUE}6. IMPORTANT COMMAND-LINE FLAGS${NC}"
echo "   ┌─ Zombie Thread Fix Flags (NEW)"
echo "   │  --skip_cpu              Skip CPU profiling entirely"
echo "   │  --num_threads N         Force N CPU threads (override SLURM)"
echo "   └─"
echo ""
echo "   ┌─ Standard Flags"
echo "   │  --model {name}          Model: resnet50/resnet152/vit_b16/bert_base/gpt2_small/simple_mlp"
echo "   │  --batch_size N          Batch size (8-256 typical)"
echo "   │  --precision {mode}      fp32/fp16/bf16"
echo "   │  --warmup N              Warmup iterations (default: 5)"
echo "   │  --measure N             Measurement iterations (default: 15)"
echo "   │  --optimizer {name}      SGD/Adam/AdamW/RMSprop/Adagrad/Adadelta"
echo "   │  --output_dir path       Output directory (default: data)"
echo "   │  --rapl                  Enable CPU RAPL energy (Linux only)"
echo "   │  --no_gpu                CPU-only profiling"
echo "   └─"
echo ""

echo -e "${BLUE}7. OUTPUT FILES${NC}"
echo "   ┌─ Structure: data/{hostname}/results/{model}/{optimizer}/{precision}/batch_{N}/run_*/"
echo "   │"
echo "   ├─ {model}_metrics.csv           ← Per-layer execution metrics (ILP input)"
echo "   ├─ {model}_metrics_gpu_partial.csv  ← GPU-only (saved early to prevent data loss)"
echo "   ├─ {model}_meta.json             ← Hardware metadata, energy totals"
echo "   └─ {model}_meta_gpu_partial.json    ← GPU-only metadata"
echo ""

echo -e "${BLUE}8. DIRECTORY STRUCTURE${NC}"
echo "   project/"
echo "   ├── src/profiler.py              ← Main profiler"
echo "   ├── config/"
echo "   │   ├── environment.yml"
echo "   │   └── requirements.txt"
echo "   ├── scripts/"
echo "   │   ├── run_experiments.sh       ← Master experiment script"
echo "   │   └── launch_grid5k.sh         ← HPC submission"
echo "   ├── data/"
echo "   │   └── <hostname>/results/      ← Generated metrics per server/node"
echo "   ├── logs/"
echo "   │   └── experiments_*.txt        ← Execution logs"
echo "   ├── tests/                       ← Unit tests"
echo "   ├── validation/                  ← Validation scripts"
echo "   ├── docs/                        ← Documentation"
echo "   └── PROJECT_STRUCTURE.md         ← This file"
echo ""

echo -e "${BLUE}9. TROUBLESHOOTING${NC}"
echo "   Problem: Process hangs at batch X"
echo "   ↳ Cause: ViT-B/16 FP16 on CPU without AVX512_FP16 (C++ emulation blocks)"
echo "   ↳ Fix: Use --skip_cpu or --precision fp32"
echo ""
echo "   Problem: OOM (Out of Memory)"
echo "   ↳ Fix: Reduce batch_size or use --skip_cpu to reduce memory usage"
echo ""
echo "   Problem: Permission denied on RAPL"
echo "   ↳ Fix: Don't use --rapl, or run with sudo (not recommended)"
echo ""

echo -e "${BLUE}10. MONITORING EXECUTION${NC}"
echo "   # Terminal 1: Start experiments"
echo "   bash scripts/run_experiments.sh"
echo ""
echo "   # Terminal 2: Monitor progress"
echo "   tail -f logs/experiments_*.txt"
echo ""
echo "   # Terminal 3: Check output files"
echo "   ls -R data/*/results/"
echo ""

echo -e "${BLUE}11. RECOMMENDED WORKFLOWS${NC}"
echo ""
echo "   ┌─ Fast GPU-only (for quick validation)"
echo "   │  Use: --skip_cpu --num_threads 16"
echo "   │  Time: ~3 min per model × metrics setup"
echo "   └─"
echo ""
echo "   ┌─ Complete profiling"
echo "   │  Use: Default settings"
echo "   │  Time: ~15 min per model"
echo "   └─"
echo ""
echo "   ┌─ HPC batch job (Grid'5000)"
echo "   │  Use: bash scripts/launch_grid5k.sh"
echo "   │  Submits via OAR scheduler"
echo "   └─"
echo ""

echo "========================================================================"
echo -e "${GREEN}✓ Project setup complete!${NC}"
echo "========================================================================"
echo ""
echo "Next steps:"
echo "  1. Verify installation: python validation/validate_code.py"
echo "  2. Profile a model: python src/profiler.py --model simple_mlp"
echo "  3. Read docs/README.md for detailed documentation"
echo ""
